version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 827472626881.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t devops-app .
      - docker tag devops-app:latest 827472626881.dkr.ecr.us-east-1.amazonaws.com/devops-app:latest

  post_build:
    commands:
      - docker push 827472626881.dkr.ecr.us-east-1.amazonaws.com/devops-app:latestwq!
